// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: getValue.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GetCoordinate {
  public static partial class coordinateService
  {
    static readonly string __ServiceName = "getCoordinate.coordinateService";

    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Google.Protobuf.WellKnownTypes.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GetCoordinate.coordinate> __Marshaller_getCoordinate_coordinate = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GetCoordinate.coordinate.Parser.ParseFrom);

    static readonly grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::GetCoordinate.coordinate> __Method_getCoordinate = new grpc::Method<global::Google.Protobuf.WellKnownTypes.Empty, global::GetCoordinate.coordinate>(
        grpc::MethodType.Unary,
        __ServiceName,
        "getCoordinate",
        __Marshaller_google_protobuf_Empty,
        __Marshaller_getCoordinate_coordinate);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GetCoordinate.GetValueReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of coordinateService</summary>
    public abstract partial class coordinateServiceBase
    {
      public virtual global::System.Threading.Tasks.Task<global::GetCoordinate.coordinate> getCoordinate(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for coordinateService</summary>
    public partial class coordinateServiceClient : grpc::ClientBase<coordinateServiceClient>
    {
      /// <summary>Creates a new client for coordinateService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public coordinateServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for coordinateService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public coordinateServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected coordinateServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected coordinateServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::GetCoordinate.coordinate getCoordinate(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getCoordinate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::GetCoordinate.coordinate getCoordinate(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_getCoordinate, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::GetCoordinate.coordinate> getCoordinateAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return getCoordinateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::GetCoordinate.coordinate> getCoordinateAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_getCoordinate, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override coordinateServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new coordinateServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(coordinateServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_getCoordinate, serviceImpl.getCoordinate).Build();
    }

  }
}
#endregion
