var searchData=
[
  ['getcoordinate_0',['GetCoordinate',['../namespace_get_coordinate.html',1,'']]],
  ['getcoordinate_1',['getCoordinate',['../classgrpc__server_1_1_coordinate_service.html#a12494f75f28fc7303ede39df8cc3e1c9',1,'grpc_server.CoordinateService.getCoordinate()'],['../class_get_coordinate_1_1coordinate_service_1_1coordinate_service_client.html#abd39acb7fbc5081d86c2872e09fdc3a3',1,'GetCoordinate.coordinateService.coordinateServiceClient.getCoordinate(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)'],['../class_get_coordinate_1_1coordinate_service_1_1coordinate_service_client.html#a6aa10002f5e3e2452e1c50f540086dcf',1,'GetCoordinate.coordinateService.coordinateServiceClient.getCoordinate(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers=null, global::System.DateTime? deadline=null, global::System.Threading.CancellationToken cancellationToken=default(global::System.Threading.CancellationToken))'],['../classget_value__pb2__grpc_1_1coordinate_service_stub.html#abacdd9fcb8547b5640103d6643b769d3',1,'getValue_pb2_grpc.coordinateServiceStub.getCoordinate'],['../classget_value__pb2__grpc_1_1coordinate_service_servicer.html#a5377e4d558f834290a0180db79b1f5ad',1,'getValue_pb2_grpc.coordinateServiceServicer.getCoordinate()'],['../classget_value__pb2__grpc_1_1coordinate_service.html#a40445306e6b0f84a8f4d36a7ab9123df',1,'getValue_pb2_grpc.coordinateService.getCoordinate()'],['../class_get_coordinate_1_1coordinate_service_1_1coordinate_service_base.html#a7dfcaee010a0792cdd8d32e5aba1fbca',1,'GetCoordinate.coordinateService.coordinateServiceBase.getCoordinate()']]],
  ['getcoordinateasync_2',['getCoordinateAsync',['../class_get_coordinate_1_1coordinate_service_1_1coordinate_service_client.html#ab8354a0207ec35c54255829727e1ea00',1,'GetCoordinate.coordinateService.coordinateServiceClient.getCoordinateAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::CallOptions options)'],['../class_get_coordinate_1_1coordinate_service_1_1coordinate_service_client.html#aae531b7a01f2952a1ee21d61330bb399',1,'GetCoordinate.coordinateService.coordinateServiceClient.getCoordinateAsync(global::Google.Protobuf.WellKnownTypes.Empty request, grpc::Metadata headers=null, global::System.DateTime? deadline=null, global::System.Threading.CancellationToken cancellationToken=default(global::System.Threading.CancellationToken))']]],
  ['gethashcode_3',['GetHashCode',['../class_get_coordinate_1_1coordinate.html#a8c06bdd330b43f976f72e1e054b70322',1,'GetCoordinate::coordinate']]],
  ['getvalue_2ecs_4',['GetValue.cs',['../_get_value_8cs.html',1,'']]],
  ['getvalue_5fpb2_5',['getValue_pb2',['../namespaceget_value__pb2.html',1,'']]],
  ['getvalue_5fpb2_2epy_6',['getValue_pb2.py',['../get_value__pb2_8py.html',1,'']]],
  ['getvalue_5fpb2_5fgrpc_7',['getValue_pb2_grpc',['../namespaceget_value__pb2__grpc.html',1,'']]],
  ['getvalue_5fpb2_5fgrpc_2epy_8',['getValue_pb2_grpc.py',['../get_value__pb2__grpc_8py.html',1,'']]],
  ['getvaluegrpc_2ecs_9',['GetValueGrpc.cs',['../_get_value_grpc_8cs.html',1,'']]],
  ['grpc_10',['grpc',['../_get_value_grpc_8cs.html#ac1caf7931d9a6735b7877748b4ae5c7a',1,'GetValueGrpc.cs']]],
  ['grpc_5fserver_11',['grpc_server',['../namespacegrpc__server.html',1,'']]],
  ['grpc_5fserver_2epy_12',['grpc_server.py',['../grpc__server_8py.html',1,'']]]
];
